spring.application.name=tokio-hotel-backend

# import env file
spring.config.import=optional:file:backend/.env[.properties]

# scalar openapi config
scalar.enabled=true
scalar.url=/openapi.yaml
scalar.path=/docs

# H2 cofig
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# activate H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# automatically create/update tables based on entities
spring.jpa.hibernate.ddl-auto=update

# show sql statements in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# add test data
spring.sql.init.mode=always

# ensure that the datasource is initialized before running the SQL scripts
spring.jpa.defer-datasource-initialization=true